#!/bin/sh

BUILD_DATE="$(date -Iseconds)"
BUILD_HOST=$(whoami)"@"$(hostname)
NMAKE_VERSION="20240522"

CC="cc"
CFLAGS='--std=c90 -g -O2 -lncurses -DNMAKE_VERSION="'$NMAKE_VERSION'" -DBUILD_DATE="'$BUILD_DATE'" -DBUILD_HOST="'$BUILD_HOST'"'

PROG="nmake"

$CC main.c mconf.c -o nmake $CFLAGS
